import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import rateLimit from 'express-rate-limit';
import pinoHttp from 'pino-http';
import { randomUUID } from 'node:crypto';
import { logger } from './lib/logger.js';
import api from './routes/api.js';
import auth from './routes/auth.js';
import ml from './routes/ml.js';
import { errorHandler, notFound } from './middleware/errors.js';
export const app = express();
app.set('trust proxy', 1);
app.use((req, res, next) => { req.id = randomUUID(); res.setHeader('X-Request-Id', req.id); next(); });
app.use(pinoHttp({ logger }));
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(',') || false, credentials: true }));
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use(rateLimit({ windowMs: 60_000, limit: 100, standardHeaders: 'draft-8', legacyHeaders: false }));
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'cvconnect-api', timestamp: new Date().toISOString() }));
app.use('/api/auth', auth);
app.use('/api/ml', ml);
app.use('/api', api);
app.use(notFound);
app.use(errorHandler);
