import 'dotenv/config';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import { app } from './app.js';
import { prisma } from './lib/prisma.js';
import { redis } from './lib/cache.js';
import { logger } from './lib/logger.js';
import { getCorsOrigin } from './lib/cors.js';
const httpServer = createServer(app);
const io = new Server(httpServer, { cors: { origin: getCorsOrigin(), credentials: true } });
app.set('io', io);
io.on('connection', socket => socket.on('subscribe', userId => { if (typeof userId === 'string') socket.join(userId); }));
const port = Number(process.env.PORT || 5000);
const shutdown = async (signal) => { logger.info({ signal }, 'Shutting down'); httpServer.close(); await prisma.$disconnect(); await redis?.quit().catch(() => {}); process.exit(0); };
process.on('SIGTERM', () => shutdown('SIGTERM')); process.on('SIGINT', () => shutdown('SIGINT'));
httpServer.listen(port, () => logger.info({ port }, 'CVConnect API listening'));
